TEST_OBJS   = test/main.o \
	      test/base64.o \
	      test/buffer.o \
	      test/md5.o \
	      test/rfc2047.o \
	      test/address.o \
	      test/url.o \
	      test/file.o

ADDRESS_OBJS	= test/address/main.o \
		  test/address/mutt_addr_append.o \
		  test/address/mutt_addr_cat.o \
		  test/address/mutt_addr_cmp.o \
		  test/address/mutt_addr_cmp_strict.o \
		  test/address/mutt_addr_copy.o \
		  test/address/mutt_addr_copy_list.o \
		  test/address/mutt_addr_for_display.o \
		  test/address/mutt_addr_free.o \
		  test/address/mutt_addr_has_recips.o \
		  test/address/mutt_addr_is_intl.o \
		  test/address/mutt_addr_is_local.o \
		  test/address/mutt_addrlist_to_intl.o \
		  test/address/mutt_addrlist_to_local.o \
		  test/address/mutt_addr_mbox_to_udomain.o \
		  test/address/mutt_addr_new.o \
		  test/address/mutt_addr_parse_list2.o \
		  test/address/mutt_addr_parse_list.o \
		  test/address/mutt_addr_qualify.o \
		  test/address/mutt_addr_remove_from_list.o \
		  test/address/mutt_addr_remove_xrefs.o \
		  test/address/mutt_addr_search.o \
		  test/address/mutt_addr_set_intl.o \
		  test/address/mutt_addr_set_local.o \
		  test/address/mutt_addr_valid_msgid.o \
		  test/address/mutt_addr_write.o \
		  test/address/mutt_addr_write_single.o

ATTACH_OBJS	= test/attach/main.o \
		  test/attach/mutt_actx_add_fp.o \
		  test/attach/mutt_actx_free_entries.o \
		  test/attach/mutt_actx_free.o \
		  test/attach/mutt_actx_add_body.o \
		  test/attach/mutt_actx_add_attach.o

BASE64_OBJS	= test/base64/main.o \
		  test/base64/mutt_b64_buffer_decode.o \
		  test/base64/mutt_b64_buffer_encode.o \
		  test/base64/mutt_b64_decode.o \
		  test/base64/mutt_b64_encode.o

BODY_OBJS	= test/body/main.o \
		  test/body/mutt_body_free.o \
		  test/body/mutt_body_cmp_strict.o \
		  test/body/mutt_body_new.o

BUFFER_OBJS	= test/buffer/main.o \
		  test/buffer/mutt_buffer_addch.o \
		  test/buffer/mutt_buffer_add_printf.o \
		  test/buffer/mutt_buffer_addstr.o \
		  test/buffer/mutt_buffer_addstr_n.o \
		  test/buffer/mutt_buffer_alloc.o \
		  test/buffer/mutt_buffer_concat_path.o \
		  test/buffer/mutt_buffer_fix_dptr.o \
		  test/buffer/mutt_buffer_free.o \
		  test/buffer/mutt_buffer_from.o \
		  test/buffer/mutt_buffer_increase_size.o \
		  test/buffer/mutt_buffer_init.o \
		  test/buffer/mutt_buffer_is_empty.o \
		  test/buffer/mutt_buffer_len.o \
		  test/buffer/mutt_buffer_new.o \
		  test/buffer/mutt_buffer_pool_free.o \
		  test/buffer/mutt_buffer_pool_get.o \
		  test/buffer/mutt_buffer_pool_release.o \
		  test/buffer/mutt_buffer_printf.o \
		  test/buffer/mutt_buffer_reset.o \
		  test/buffer/mutt_buffer_strcpy.o \
		  test/buffer/mutt_buffer_strcpy_n.o

CHARSET_OBJS	= test/charset/main.o \
		  test/charset/mutt_ch_canonical_charset.o \
		  test/charset/mutt_ch_charset_lookup.o \
		  test/charset/mutt_ch_check.o \
		  test/charset/mutt_ch_check_charset.o \
		  test/charset/mutt_ch_choose.o \
		  test/charset/mutt_ch_chscmp.o \
		  test/charset/mutt_ch_convert_nonmime_string.o \
		  test/charset/mutt_ch_convert_string.o \
		  test/charset/mutt_ch_fgetconv.o \
		  test/charset/mutt_ch_fgetconv_close.o \
		  test/charset/mutt_ch_fgetconv_open.o \
		  test/charset/mutt_ch_fgetconvs.o \
		  test/charset/mutt_ch_get_default_charset.o \
		  test/charset/mutt_ch_get_langinfo_charset.o \
		  test/charset/mutt_ch_iconv.o \
		  test/charset/mutt_ch_iconv_lookup.o \
		  test/charset/mutt_ch_iconv_open.o \
		  test/charset/mutt_ch_lookup_add.o \
		  test/charset/mutt_ch_lookup_remove.o \
		  test/charset/mutt_ch_set_charset.o

CONFIG_OBJS	= test/config/main.o test/config/account.o \
		  test/config/address.o test/config/bool.o \
		  test/config/command.o test/config/common.o test/config/dump.o \
		  test/config/initial.o test/config/long.o \
		  test/config/magic.o test/config/mbtable.o \
		  test/config/number.o test/config/path.o test/config/quad.o \
		  test/config/regex.o test/config/set.o test/config/sort.o \
		  test/config/string.o test/config/synonym.o

DATE_OBJS	= test/date/main.o \
		  test/date/mutt_date_add_timeout.o \
		  test/date/mutt_date_check_month.o \
		  test/date/mutt_date_gmtime.o \
		  test/date/mutt_date_is_day_name.o \
		  test/date/mutt_date_localtime.o \
		  test/date/mutt_date_localtime_format.o \
		  test/date/mutt_date_local_tz.o \
		  test/date/mutt_date_make_date.o \
		  test/date/mutt_date_make_imap.o \
		  test/date/mutt_date_make_time.o \
		  test/date/mutt_date_make_tls.o \
		  test/date/mutt_date_normalize_time.o \
		  test/date/mutt_date_parse_date.o \
		  test/date/mutt_date_parse_imap.o

EMAIL_OBJS	= test/email/main.o \
		  test/email/mutt_email_new.o \
		  test/email/mutt_email_free.o \
		  test/email/mutt_email_size.o \
		  test/email/mutt_email_cmp_strict.o

ENVELOPE_OBJS	= test/envelope/main.o \
		  test/envelope/mutt_env_free.o \
		  test/envelope/mutt_env_cmp_strict.o \
		  test/envelope/mutt_env_to_local.o \
		  test/envelope/mutt_env_merge.o \
		  test/envelope/mutt_env_new.o \
		  test/envelope/mutt_env_to_intl.o

ENVLIST_OBJS	= test/envlist/main.o \
		  test/envlist/mutt_envlist_free.o \
		  test/envlist/mutt_envlist_getlist.o \
		  test/envlist/mutt_envlist_init.o \
		  test/envlist/mutt_envlist_set.o \
		  test/envlist/mutt_envlist_unset.o

FILE_OBJS	= test/file/main.o \
		  test/file/mutt_file_check_empty.o \
		  test/file/mutt_file_chmod_add.o \
		  test/file/mutt_file_chmod_add_stat.o \
		  test/file/mutt_file_chmod.o \
		  test/file/mutt_file_chmod_rm.o \
		  test/file/mutt_file_chmod_rm_stat.o \
		  test/file/mutt_file_copy_bytes.o \
		  test/file/mutt_file_copy_stream.o \
		  test/file/mutt_file_decrease_mtime.o \
		  test/file/mutt_file_expand_fmt.o \
		  test/file/mutt_file_expand_fmt_quote.o \
		  test/file/mutt_file_fclose.o \
		  test/file/mutt_file_fopen.o \
		  test/file/mutt_file_fsync_close.o \
		  test/file/mutt_file_get_size.o \
		  test/file/mutt_file_get_stat_timespec.o \
		  test/file/mutt_file_iter_line.o \
		  test/file/mutt_file_lock.o \
		  test/file/mutt_file_map_lines.o \
		  test/file/mutt_file_mkdir.o \
		  test/file/mutt_file_mkstemp_full.o \
		  test/file/mutt_file_open.o \
		  test/file/mutt_file_quote_filename.o \
		  test/file/mutt_file_read_keyword.o \
		  test/file/mutt_file_read_line.o \
		  test/file/mutt_file_rename.o \
		  test/file/mutt_file_rmtree.o \
		  test/file/mutt_file_safe_rename.o \
		  test/file/mutt_file_sanitize_filename.o \
		  test/file/mutt_file_sanitize_regex.o \
		  test/file/mutt_file_set_mtime.o \
		  test/file/mutt_file_stat_compare.o \
		  test/file/mutt_file_stat_timespec_compare.o \
		  test/file/mutt_file_symlink.o \
		  test/file/mutt_file_timespec_compare.o \
		  test/file/mutt_file_touch_atime.o \
		  test/file/mutt_file_unlink.o \
		  test/file/mutt_file_unlink_empty.o \
		  test/file/mutt_file_unlock.o

GROUP_OBJS	= test/group/main.o \
		  test/group/mutt_grouplist_add_addrlist.o \
		  test/group/mutt_grouplist_add.o \
		  test/group/mutt_grouplist_add_regex.o \
		  test/group/mutt_grouplist_clear.o \
		  test/group/mutt_grouplist_destroy.o \
		  test/group/mutt_grouplist_free.o \
		  test/group/mutt_grouplist_init.o \
		  test/group/mutt_grouplist_remove_addrlist.o \
		  test/group/mutt_grouplist_remove_regex.o \
		  test/group/mutt_group_match.o \
		  test/group/mutt_pattern_group.o

HASH_OBJS	= test/hash/main.o \
		  test/hash/mutt_hash_delete.o \
		  test/hash/mutt_hash_find_bucket.o \
		  test/hash/mutt_hash_find.o \
		  test/hash/mutt_hash_find_elem.o \
		  test/hash/mutt_hash_free.o \
		  test/hash/mutt_hash_insert.o \
		  test/hash/mutt_hash_int_delete.o \
		  test/hash/mutt_hash_int_find.o \
		  test/hash/mutt_hash_int_insert.o \
		  test/hash/mutt_hash_int_new.o \
		  test/hash/mutt_hash_new.o \
		  test/hash/mutt_hash_set_destructor.o \
		  test/hash/mutt_hash_typed_insert.o \
		  test/hash/mutt_hash_walk.o

HISTORY_OBJS	= test/history/main.o \
		  test/history/mutt_hist_add.o \
		  test/history/mutt_hist_at_scratch.o \
		  test/history/mutt_hist_free.o \
		  test/history/mutt_hist_init.o \
		  test/history/mutt_hist_next.o \
		  test/history/mutt_hist_prev.o \
		  test/history/mutt_hist_read_file.o \
		  test/history/mutt_hist_reset_state.o \
		  test/history/mutt_hist_save_scratch.o \
		  test/history/mutt_hist_search.o

IDNA_OBJS	= test/idna/main.o \
		  test/idna/mutt_idna_intl_to_local.o \
		  test/idna/mutt_idna_local_to_intl.o \
		  test/idna/mutt_idna_print_version.o \
		  test/idna/mutt_idna_to_ascii_lz.o

LIST_OBJS	= test/list/main.o \
		  test/list/mutt_list_clear.o \
		  test/list/mutt_list_compare.o \
		  test/list/mutt_list_find.o \
		  test/list/mutt_list_free.o \
		  test/list/mutt_list_free_type.o \
		  test/list/mutt_list_insert_after.o \
		  test/list/mutt_list_insert_head.o \
		  test/list/mutt_list_insert_tail.o \
		  test/list/mutt_list_match.o

LOGGING_OBJS	= test/logging/main.o \
		  test/logging/log_disp_file.o \
		  test/logging/log_disp_queue.o \
		  test/logging/log_disp_terminal.o \
		  test/logging/log_file_close.o \
		  test/logging/log_file_open.o \
		  test/logging/log_file_running.o \
		  test/logging/log_file_set_filename.o \
		  test/logging/log_file_set_level.o \
		  test/logging/log_file_set_version.o \
		  test/logging/log_queue_add.o \
		  test/logging/log_queue_empty.o \
		  test/logging/log_queue_flush.o \
		  test/logging/log_queue_save.o \
		  test/logging/log_queue_set_max_size.o

MAPPING_OBJS	= test/mapping/main.o \
		  test/mapping/mutt_map_get_name.o \
		  test/mapping/mutt_map_get_value.o

MBYTE_OBJS	= test/mbyte/main.o \
		  test/mbyte/mutt_mb_charlen.o \
		  test/mbyte/mutt_mb_filter_unprintable.o \
		  test/mbyte/mutt_mb_get_initials.o \
		  test/mbyte/mutt_mb_is_display_corrupting_utf8.o \
		  test/mbyte/mutt_mb_is_lower.o \
		  test/mbyte/mutt_mb_is_shell_char.o \
		  test/mbyte/mutt_mb_mbstowcs.o \
		  test/mbyte/mutt_mb_wcstombs.o \
		  test/mbyte/mutt_mb_wcswidth.o \
		  test/mbyte/mutt_mb_wcwidth.o \
		  test/mbyte/mutt_mb_width.o \
		  test/mbyte/mutt_mb_width_ceiling.o

MD5_OBJS	= test/md5/main.o \
		  test/md5/mutt_md5_bytes.o \
		  test/md5/mutt_md5.o \
		  test/md5/mutt_md5_finish_ctx.o \
		  test/md5/mutt_md5_init_ctx.o \
		  test/md5/mutt_md5_process_bytes.o \
		  test/md5/mutt_md5_process.o \
		  test/md5/mutt_md5_toascii.o

MEMORY_OBJS	= test/memory/main.o \
		  test/memory/mutt_mem_calloc.o \
		  test/memory/mutt_mem_free.o \
		  test/memory/mutt_mem_malloc.o \
		  test/memory/mutt_mem_realloc.o

PATH_OBJS	= test/path/main.o \
		  test/path/mutt_path_abbr_folder.o \
		  test/path/mutt_path_basename.o \
		  test/path/mutt_path_canon.o \
		  test/path/mutt_path_concat.o \
		  test/path/mutt_path_concatn.o \
		  test/path/mutt_path_dirname.o \
		  test/path/mutt_path_escape.o \
		  test/path/mutt_path_getcwd.o \
		  test/path/mutt_path_parent.o \
		  test/path/mutt_path_pretty.o \
		  test/path/mutt_path_realpath.o \
		  test/path/mutt_path_tidy.o \
		  test/path/mutt_path_tidy_dotdot.o \
		  test/path/mutt_path_tidy_slash.o \
		  test/path/mutt_path_to_absolute.o

PATTERN_OBJS	= test/pattern/main.o \
		  test/pattern/comp.o \
		  test/pattern/dummy.o \
		  test/pattern/extract.o \
		  pattern.o

REGEX_OBJS	= test/regex/main.o \
		  test/regex/mutt_regex_compile.o \
		  test/regex/mutt_regex_free.o \
		  test/regex/mutt_regexlist_add.o \
		  test/regex/mutt_regexlist_free.o \
		  test/regex/mutt_regexlist_match.o \
		  test/regex/mutt_regexlist_new.o \
		  test/regex/mutt_regexlist_remove.o \
		  test/regex/mutt_regex_new.o \
		  test/regex/mutt_replacelist_add.o \
		  test/regex/mutt_replacelist_apply.o \
		  test/regex/mutt_replacelist_free.o \
		  test/regex/mutt_replacelist_match.o \
		  test/regex/mutt_replacelist_new.o \
		  test/regex/mutt_replacelist_remove.o

SHA1_OBJS	= test/sha1/main.o \
		  test/sha1/mutt_sha1_final.o \
		  test/sha1/mutt_sha1_init.o \
		  test/sha1/mutt_sha1_transform.o \
		  test/sha1/mutt_sha1_update.o

SIGNAL_OBJS	= test/signal/main.o \
		  test/signal/mutt_sig_allow_interrupt.o \
		  test/signal/mutt_sig_block.o \
		  test/signal/mutt_sig_block_system.o \
		  test/signal/mutt_sig_empty_handler.o \
		  test/signal/mutt_sig_exit_handler.o \
		  test/signal/mutt_sig_init.o \
		  test/signal/mutt_sig_unblock.o \
		  test/signal/mutt_sig_unblock_system.o

STRING_OBJS	= test/string/main.o \
		  test/string/mutt_str_adjust.o \
		  test/string/mutt_str_append_item.o \
		  test/string/mutt_str_asprintf.o \
		  test/string/mutt_str_atoi.o \
		  test/string/mutt_str_atol.o \
		  test/string/mutt_str_atos.o \
		  test/string/mutt_str_atoui.o \
		  test/string/mutt_str_atoul.o \
		  test/string/mutt_str_atoull.o \
		  test/string/mutt_str_dequote_comment.o \
		  test/string/mutt_str_find_word.o \
		  test/string/mutt_str_getenv.o \
		  test/string/mutt_str_inline_replace.o \
		  test/string/mutt_str_is_ascii.o \
		  test/string/mutt_str_is_email_wsp.o \
		  test/string/mutt_str_lws_len.o \
		  test/string/mutt_str_lws_rlen.o \
		  test/string/mutt_str_next_word.o \
		  test/string/mutt_str_pretty_size.o \
		  test/string/mutt_str_remall_strcasestr.o \
		  test/string/mutt_str_remove_trailing_ws.o \
		  test/string/mutt_str_replace.o \
		  test/string/mutt_str_rstrnstr.o \
		  test/string/mutt_str_skip_email_wsp.o \
		  test/string/mutt_str_skip_whitespace.o \
		  test/string/mutt_str_split.o \
		  test/string/mutt_str_startswith.o \
		  test/string/mutt_str_strcasecmp.o \
		  test/string/mutt_str_strcasestr.o \
		  test/string/mutt_str_strcat.o \
		  test/string/mutt_str_strchrnul.o \
		  test/string/mutt_str_strcmp.o \
		  test/string/mutt_str_strcoll.o \
		  test/string/mutt_str_strdup.o \
		  test/string/mutt_str_strfcpy.o \
		  test/string/mutt_str_stristr.o \
		  test/string/mutt_str_strlen.o \
		  test/string/mutt_str_strlower.o \
		  test/string/mutt_str_strncasecmp.o \
		  test/string/mutt_str_strncat.o \
		  test/string/mutt_str_strncmp.o \
		  test/string/mutt_str_strnfcpy.o \
		  test/string/mutt_str_substr_cpy.o \
		  test/string/mutt_str_substr_dup.o \
		  test/string/mutt_str_sysexit.o \
		  test/string/mutt_str_word_casecmp.o

CFLAGS	+= -I$(SRCDIR)/test

TEST_BINARY = test/neomutt-test$(EXEEXT)

TEST_ADDRESS = test/address-test$(EXEEXT)

TEST_ATTACH = test/attach-test$(EXEEXT)

TEST_BASE64 = test/base64-test$(EXEEXT)

TEST_BODY = test/body-test$(EXEEXT)

TEST_BUFFER = test/buffer-test$(EXEEXT)

TEST_CHARSET = test/charset-test$(EXEEXT)

TEST_CONFIG = test/config-test$(EXEEXT)

TEST_DATE = test/date-test$(EXEEXT)

TEST_EMAIL = test/email-test$(EXEEXT)

TEST_ENVELOPE = test/envelope-test$(EXEEXT)

TEST_ENVLIST = test/envlist-test$(EXEEXT)

TEST_FILE = test/file-test$(EXEEXT)

TEST_GROUP = test/group-test$(EXEEXT)

TEST_HASH = test/hash-test$(EXEEXT)

TEST_HISTORY = test/history-test$(EXEEXT)

TEST_IDNA = test/idna-test$(EXEEXT)

TEST_LIST = test/list-test$(EXEEXT)

TEST_LOGGING = test/logging-test$(EXEEXT)

TEST_MAPPING = test/mapping-test$(EXEEXT)

TEST_MBYTE = test/mbyte-test$(EXEEXT)

TEST_MD5 = test/md5-test$(EXEEXT)

TEST_MEMORY = test/memory-test$(EXEEXT)

TEST_PATH = test/path-test$(EXEEXT)

TEST_PATTERN = test/pattern-test$(EXEEXT)

TEST_REGEX = test/regex-test$(EXEEXT)

TEST_SHA1 = test/sha1-test$(EXEEXT)

TEST_SIGNAL = test/signal-test$(EXEEXT)

TEST_STRING = test/string-test$(EXEEXT)

.PHONY: test
test: $(TEST_BINARY) $(TEST_ADDRESS) $(TEST_ATTACH) $(TEST_BASE64) $(TEST_BODY) $(TEST_BUFFER) $(TEST_CHARSET) $(TEST_CONFIG) $(TEST_DATE) $(TEST_EMAIL) $(TEST_ENVELOPE) $(TEST_ENVLIST) $(TEST_FILE) $(TEST_GROUP) $(TEST_HASH) $(TEST_HISTORY) $(TEST_IDNA) $(TEST_LIST) $(TEST_LOGGING) $(TEST_MAPPING) $(TEST_MBYTE) $(TEST_MD5) $(TEST_MEMORY) $(TEST_PATH) $(TEST_PATTERN) $(TEST_REGEX) $(TEST_SHA1) $(TEST_SIGNAL) $(TEST_STRING)
	$(TEST_BINARY)
	$(TEST_ADDRESS)
	$(TEST_ATTACH)
	$(TEST_BASE64)
	$(TEST_BODY)
	$(TEST_BUFFER)
	$(TEST_CONFIG)
	$(TEST_DATE)
	$(TEST_EMAIL)
	$(TEST_ENVELOPE)
	$(TEST_ENVLIST)
	$(TEST_FILE)
	$(TEST_GROUP)
	$(TEST_HASH)
	$(TEST_HISTORY)
	$(TEST_IDNA)
	$(TEST_LIST)
	$(TEST_LOGGING)
	$(TEST_MAPPING)
	$(TEST_MBYTE)
	$(TEST_MD5)
	$(TEST_MEMORY)
	$(TEST_PATH)
	$(TEST_PATTERN)
	$(TEST_REGEX)
	$(TEST_SHA1)
	$(TEST_SIGNAL)
	$(TEST_STRING)

$(TEST_BINARY): $(TEST_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(TEST_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_ADDRESS): $(PWD)/test/address $(ADDRESS_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(ADDRESS_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_ATTACH): $(PWD)/test/attach $(ATTACH_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(ATTACH_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_BASE64): $(PWD)/test/base64 $(BASE64_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(BASE64_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_BODY): $(PWD)/test/body $(BODY_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(BODY_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_BUFFER): $(PWD)/test/buffer $(BUFFER_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(BUFFER_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_CHARSET): $(PWD)/test/charset $(CHARSET_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(CHARSET_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_CONFIG): $(PWD)/test/config $(CONFIG_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(CONFIG_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_DATE): $(PWD)/test/date $(DATE_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(DATE_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_EMAIL): $(PWD)/test/email $(EMAIL_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(EMAIL_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_ENVELOPE): $(PWD)/test/envelope $(ENVELOPE_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(ENVELOPE_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_ENVLIST): $(PWD)/test/envlist $(ENVLIST_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(ENVLIST_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_FILE): $(PWD)/test/file $(FILE_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(FILE_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_GROUP): $(PWD)/test/group $(GROUP_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(GROUP_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_HASH): $(PWD)/test/hash $(HASH_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(HASH_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_HISTORY): $(PWD)/test/history $(HISTORY_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(HISTORY_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_IDNA): $(PWD)/test/idna $(IDNA_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(IDNA_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_LIST): $(PWD)/test/list $(LIST_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(LIST_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_LOGGING): $(PWD)/test/logging $(LOGGING_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(LOGGING_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_MAPPING): $(PWD)/test/mapping $(MAPPING_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(MAPPING_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_MBYTE): $(PWD)/test/mbyte $(MBYTE_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(MBYTE_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_MD5): $(PWD)/test/md5 $(MD5_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(MD5_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_MEMORY): $(PWD)/test/memory $(MEMORY_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(MEMORY_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_PATH): $(PWD)/test/path $(PATH_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(PATH_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_PATTERN): $(PWD)/test/pattern $(PATTERN_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(PATTERN_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_REGEX): $(PWD)/test/regex $(REGEX_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(REGEX_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_SHA1): $(PWD)/test/sha1 $(SHA1_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(SHA1_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_SIGNAL): $(PWD)/test/signal $(SIGNAL_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(SIGNAL_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(TEST_STRING): $(PWD)/test/string $(STRING_OBJS) $(MUTTLIBS)
	$(CC) -o $@ $(STRING_OBJS) $(MUTTLIBS) $(LDFLAGS) $(LIBS)

$(PWD)/test/address:
	$(MKDIR_P) $(PWD)/test/address

$(PWD)/test/attach:
	$(MKDIR_P) $(PWD)/test/attach

$(PWD)/test/base64:
	$(MKDIR_P) $(PWD)/test/base64

$(PWD)/test/body:
	$(MKDIR_P) $(PWD)/test/body

$(PWD)/test/buffer:
	$(MKDIR_P) $(PWD)/test/buffer

$(PWD)/test/charset:
	$(MKDIR_P) $(PWD)/test/charset

$(PWD)/test/config:
	$(MKDIR_P) $(PWD)/test/config

$(PWD)/test/date:
	$(MKDIR_P) $(PWD)/test/date

$(PWD)/test/email:
	$(MKDIR_P) $(PWD)/test/email

$(PWD)/test/envelope:
	$(MKDIR_P) $(PWD)/test/envelope

$(PWD)/test/envlist:
	$(MKDIR_P) $(PWD)/test/envlist

$(PWD)/test/file:
	$(MKDIR_P) $(PWD)/test/file

$(PWD)/test/group:
	$(MKDIR_P) $(PWD)/test/group

$(PWD)/test/hash:
	$(MKDIR_P) $(PWD)/test/hash

$(PWD)/test/history:
	$(MKDIR_P) $(PWD)/test/history

$(PWD)/test/idna:
	$(MKDIR_P) $(PWD)/test/idna

$(PWD)/test/list:
	$(MKDIR_P) $(PWD)/test/list

$(PWD)/test/logging:
	$(MKDIR_P) $(PWD)/test/logging

$(PWD)/test/mapping:
	$(MKDIR_P) $(PWD)/test/mapping

$(PWD)/test/mbyte:
	$(MKDIR_P) $(PWD)/test/mbyte

$(PWD)/test/md5:
	$(MKDIR_P) $(PWD)/test/md5

$(PWD)/test/memory:
	$(MKDIR_P) $(PWD)/test/memory

$(PWD)/test/path:
	$(MKDIR_P) $(PWD)/test/path

$(PWD)/test/pattern:
	$(MKDIR_P) $(PWD)/test/pattern

$(PWD)/test/regex:
	$(MKDIR_P) $(PWD)/test/regex

$(PWD)/test/sha1:
	$(MKDIR_P) $(PWD)/test/sha1

$(PWD)/test/signal:
	$(MKDIR_P) $(PWD)/test/signal

$(PWD)/test/string:
	$(MKDIR_P) $(PWD)/test/string

all-test: $(TEST_BINARY) $(TEST_ADDRESS) $(TEST_ATTACH) $(TEST_BASE64) $(TEST_BODY) $(TEST_BUFFER) $(TEST_CHARSET) $(TEST_CONFIG) $(TEST_DATE) $(TEST_EMAIL) $(TEST_ENVELOPE) $(TEST_ENVLIST) $(TEST_FILE) $(TEST_GROUP) $(TEST_HASH) $(TEST_HISTORY) $(TEST_IDNA) $(TEST_LIST) $(TEST_LOGGING) $(TEST_MAPPING) $(TEST_MBYTE) $(TEST_MD5) $(TEST_MEMORY) $(TEST_PATH) $(TEST_PATTERN) $(TEST_REGEX) $(TEST_SHA1) $(TEST_SIGNAL) $(TEST_STRING)

clean-test:
	$(RM) $(TEST_BINARY) $(TEST_OBJS) $(TEST_OBJS:.o=.Po) \
	      $(TEST_ADDRESS) $(ADDRESS_OBJS) $(ADDRESS_OBJS:.o=.Po) \
	      $(TEST_ATTACH) $(ATTACH_OBJS) $(ATTACH_OBJS:.o=.Po) \
	      $(TEST_BASE64) $(BASE64_OBJS) $(BASE64_OBJS:.o=.Po) \
	      $(TEST_BODY) $(BODY_OBJS) $(BODY_OBJS:.o=.Po) \
	      $(TEST_BUFFER) $(BUFFER_OBJS) $(BUFFER_OBJS:.o=.Po) \
	      $(TEST_CHARSET) $(CHARSET_OBJS) $(CHARSET_OBJS:.o=.Po) \
	      $(TEST_CONFIG) $(CONFIG_OBJS) $(CONFIG_OBJS:.o=.Po) \
	      $(TEST_DATE) $(DATE_OBJS) $(DATE_OBJS:.o=.Po) \
	      $(TEST_EMAIL) $(EMAIL_OBJS) $(EMAIL_OBJS:.o=.Po) \
	      $(TEST_ENVELOPE) $(ENVELOPE_OBJS) $(ENVELOPE_OBJS:.o=.Po) \
	      $(TEST_ENVLIST) $(ENVLIST_OBJS) $(ENVLIST_OBJS:.o=.Po) \
	      $(TEST_FILE) $(FILE_OBJS) $(FILE_OBJS:.o=.Po) \
	      $(TEST_GROUP) $(GROUP_OBJS) $(GROUP_OBJS:.o=.Po) \
	      $(TEST_HASH) $(HASH_OBJS) $(HASH_OBJS:.o=.Po) \
	      $(TEST_HISTORY) $(HISTORY_OBJS) $(HISTORY_OBJS:.o=.Po) \
	      $(TEST_IDNA) $(IDNA_OBJS) $(IDNA_OBJS:.o=.Po) \
	      $(TEST_LIST) $(LIST_OBJS) $(LIST_OBJS:.o=.Po) \
	      $(TEST_LOGGING) $(LOGGING_OBJS) $(LOGGING_OBJS:.o=.Po) \
	      $(TEST_MAPPING) $(MAPPING_OBJS) $(MAPPING_OBJS:.o=.Po) \
	      $(TEST_MBYTE) $(MBYTE_OBJS) $(MBYTE_OBJS:.o=.Po) \
	      $(TEST_MD5) $(MD5_OBJS) $(MD5_OBJS:.o=.Po) \
	      $(TEST_MEMORY) $(MEMORY_OBJS) $(MEMORY_OBJS:.o=.Po) \
	      $(TEST_PATH) $(PATH_OBJS) $(PATH_OBJS:.o=.Po) \
	      $(TEST_PATTERN) $(PATTERN_OBJS) $(PATTERN_OBJS:.o=.Po) \
	      $(TEST_REGEX) $(REGEX_OBJS) $(REGEX_OBJS:.o=.Po) \
	      $(TEST_SHA1) $(SHA1_OBJS) $(SHA1_OBJS:.o=.Po) \
	      $(TEST_SIGNAL) $(SIGNAL_OBJS) $(SIGNAL_OBJS:.o=.Po) \
	      $(TEST_STRING) $(STRING_OBJS) $(STRING_OBJS:.o=.Po)

install-test:
uninstall-test:

TEST_DEPFILES = $(TEST_OBJS:.o=.Po)
-include $(TEST_DEPFILES)

ADDRESS_DEPFILES = $(ADDRESS_OBJS:.o=.Po)
-include $(ADDRESS_DEPFILES)

ATTACH_DEPFILES = $(ATTACH_OBJS:.o=.Po)
-include $(ATTACH_DEPFILES)

BASE64_DEPFILES = $(BASE64_OBJS:.o=.Po)
-include $(BASE64_DEPFILES)

BODY_DEPFILES = $(BODY_OBJS:.o=.Po)
-include $(BODY_DEPFILES)

BUFFER_DEPFILES = $(BUFFER_OBJS:.o=.Po)
-include $(BUFFER_DEPFILES)

CHARSET_DEPFILES = $(CHARSET_OBJS:.o=.Po)
-include $(CHARSET_DEPFILES)

CONFIG_DEPFILES = $(CONFIG_OBJS:.o=.Po)
-include $(CONFIG_DEPFILES)

DATE_DEPFILES = $(DATE_OBJS:.o=.Po)
-include $(DATE_DEPFILES)

EMAIL_DEPFILES = $(EMAIL_OBJS:.o=.Po)
-include $(EMAIL_DEPFILES)

ENVELOPE_DEPFILES = $(ENVELOPE_OBJS:.o=.Po)
-include $(ENVELOPE_DEPFILES)

ENVLIST_DEPFILES = $(ENVLIST_OBJS:.o=.Po)
-include $(ENVLIST_DEPFILES)

FILE_DEPFILES = $(FILE_OBJS:.o=.Po)
-include $(FILE_DEPFILES)

GROUP_DEPFILES = $(GROUP_OBJS:.o=.Po)
-include $(GROUP_DEPFILES)

HASH_DEPFILES = $(HASH_OBJS:.o=.Po)
-include $(HASH_DEPFILES)

HISTORY_DEPFILES = $(HISTORY_OBJS:.o=.Po)
-include $(HISTORY_DEPFILES)

IDNA_DEPFILES = $(IDNA_OBJS:.o=.Po)
-include $(IDNA_DEPFILES)

LIST_DEPFILES = $(LIST_OBJS:.o=.Po)
-include $(LIST_DEPFILES)

LOGGING_DEPFILES = $(LOGGING_OBJS:.o=.Po)
-include $(LOGGING_DEPFILES)

MAPPING_DEPFILES = $(MAPPING_OBJS:.o=.Po)
-include $(MAPPING_DEPFILES)

MBYTE_DEPFILES = $(MBYTE_OBJS:.o=.Po)
-include $(MBYTE_DEPFILES)

MD5_DEPFILES = $(MD5_OBJS:.o=.Po)
-include $(MD5_DEPFILES)

MEMORY_DEPFILES = $(MEMORY_OBJS:.o=.Po)
-include $(MEMORY_DEPFILES)

PATH_DEPFILES = $(PATH_OBJS:.o=.Po)
-include $(PATH_DEPFILES)

PATTERN_DEPFILES = $(PATTERN_OBJS:.o=.Po)
-include $(PATTERN_DEPFILES)

REGEX_DEPFILES = $(REGEX_OBJS:.o=.Po)
-include $(REGEX_DEPFILES)

SHA1_DEPFILES = $(SHA1_OBJS:.o=.Po)
-include $(SHA1_DEPFILES)

SIGNAL_DEPFILES = $(SIGNAL_OBJS:.o=.Po)
-include $(SIGNAL_DEPFILES)

STRING_DEPFILES = $(STRING_OBJS:.o=.Po)
-include $(STRING_DEPFILES)

# vim: set ts=8 noexpandtab:
