path_classifiers:
  generated:
    - config.h
    - conststrings.c
    - git_ver.c
    - hcache/hcversion.h
  library:
    - autosetup
    - contrib
  test:
    - test
  docs:
    - doc
    - doxygen

queries:
  - exclude: cpp/fixme-comment

extraction:
  cpp:
    prepare:
      packages:
        - autopoint
        - docbook-simple
        - docbook-xsl
        - gettext
        - jimsh
        - libdb-dev
        - libgdbm-dev
        - libgpgme-dev
        - libgss-dev
        - libkyotocabinet-dev
        - liblmdb-dev
        - liblua5.2-dev
        - libncursesw5
        - libncursesw5-dev
        - libnotmuch-dev
        - libqdbm-dev
        - libsasl2-dev
        - libssl-dev
        - libtokyocabinet-dev
        - libxml2-utils
        - lua5.2
        - lynx
        - w3m
        - xsltproc
    configure:
      command:
        - ./configure --bdb --gdbm --gnutls --gpgme --homespool --kyotocabinet --lmdb --lua --mixmaster --notmuch --qdbm --sasl --tokyocabinet --with-domain=example.com --with-lock=flock
    index:
      build_command:
        - make -j2 -s

