#!/bin/sh

if autoreconf --install && ./configure "$@"
then
  echo
  echo "The mutt source code was successfully prepared and configured."
  echo "Type   make && make install   to build and install mutt."
  echo
else
  echo
  echo "Some part of the preparation process failed."
  echo "Please refer to https://www.neomutt.org/dev/newbie-tutorial for details."
  echo
  exit 1
fi
