FUZZ_OBJS   = fuzz/address.o fuzz/date.o

CFLAGS	+= -I$(SRCDIR)/fuzz

FUZZ_ADDRESS = fuzz/address-fuzz$(EXEEXT)
FUZZ_DATE = fuzz/date-fuzz$(EXEEXT)

.PHONY: fuzz
fuzz: $(FUZZ_ADDRESS) $(FUZZ_DATE)

$(FUZZ_ADDRESS): fuzz/address.o $(NEOMUTTOBJS) $(MUTTLIBS) $(NEOMUTTLIBS)
	$(CXX) $(CXXFLAGS) -o $@ fuzz/address.o $(NEOMUTTOBJS) $(MUTTLIBS) $(NEOMUTTLIBS) $(LDFLAGS) $(LIBS) $(LIB_FUZZING_ENGINE)

$(FUZZ_DATE): fuzz/date.o $(NEOMUTTOBJS) $(MUTTLIBS) $(NEOMUTTLIBS)
	$(CXX) $(CXXFLAGS) -o $@ fuzz/date.o $(NEOMUTTOBJS) $(MUTTLIBS) $(NEOMUTTLIBS) $(LDFLAGS) $(LIBS) $(LIB_FUZZING_ENGINE)

all-fuzz: $(FUZZ_ADDRESS) $(FUZZ_DATE)

clean-fuzz:
	$(RM) $(FUZZ_ADDRESS) $(FUZZ_DATE) $(FUZZ_OBJS) $(FUZZ_OBJS:.o=.Po)

install-fuzz:
uninstall-fuzz:

FUZZ_DEPFILES = $(FUZZ_OBJS:.o=.Po)
-include $(FUZZ_DEPFILES)

# vim: set ts=8 noexpandtab:
