.\" -*-nroff-*-
.\"
.\"
.\"     Copyright (C) 1996-2000 Thomas Roessler <roessler@does-not-exist.org>
.\" 
.\"     This program is free software; you can redistribute it and/or modify
.\"     it under the terms of the GNU General Public License as published by
.\"     the Free Software Foundation; either version 2 of the License, or
.\"     (at your option) any later version.
.\" 
.\"     This program is distributed in the hope that it will be useful,
.\"     but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"     GNU General Public License for more details.
.\" 
.\"     You should have received a copy of the GNU General Public License
.\"     along with this program; if not, write to the Free Software
.\"     Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
.\"
.TH flea 1 "January 2005" Unix "User Manuals"
.SH NAME
flea \- Report a bug (or rather a flea) in mutt. (OBSOLETE)
.SH DESCRIPTION
.PP
.B flea
used to be a shell script which helped you to submit a bug report against the 
.BR mutt (1)
mail user agent.
.PP
The mutt bug tracking system broke down under the spam thrown at it and
was shut down in January 2005.  To report a bug in mutt, please use
your system's bug reporting system if mutt came as part of your
system, or refer to the mutt web site at
.I http://www.mutt.org
for more information.
.PP
.B flea
is now a shell script that prints a short error message and exits.
.SH
AUTHOR
.PP
.B flea
and this manual page were written by Thomas Roessler
<roessler@does-not-exist.org>.
