#!/usr/bin/perl -w

use strict;

my (%OPS, %MAP_FUNC_TO_OP, %MAP_OP_TO_SEQSET, %DOC, $map);
my (%GENERIC_OP_TO_FUNC, %INDEX_OP_TO_FUNC);

my $xml = shift @ARGV;

open F, "cat @ARGV |" or die "OPS*: $!";
while (<F>) {
  if ( /^\s+_fmt\((\w+),\s+N_\("(.+)"\)\)/ ) {
    $OPS{$1} = $2;
  }
}
close F;

# Slurp all input so the maps can be processed in two passes.  This makes
# the cross-referencing order-independent: the inherited maps ('index' and
# 'generic') may appear in the input after the maps that inherit from them.
my @lines = <STDIN>;

# Pass 1: parse the MenuFuncOp tables (function -> op) for every map.
for (my $i = 0; $i <= $#lines; $i++) {
  $_ = $lines[$i];
  if (/^(?:static )*const struct MenuFuncOp Op.*{ \/\* map: (.*) \*\//) {
    $map = $1;
    $DOC{$map} = "";
    $MAP_FUNC_TO_OP{$map} = {};
    $MAP_OP_TO_SEQSET{$map} = {};
    while (defined($_ = $lines[++$i])) {
      last if (/^}/);
      if (/^\s*\*\*\s*(.*)/) {
        $DOC{$map} .= "$1\n";
      }
      elsif (/{\s*"(.+)"\s*,\s*(\w+)\s*}/) {
        my ($function, $op) = ($1, $2);
        die "unknown OP $op" unless $OPS{$op};
        $MAP_OP_TO_SEQSET{$map}->{$op} = {};
        if (!exists($MAP_FUNC_TO_OP{$map}->{$function})) {
          $MAP_FUNC_TO_OP{$map}->{$function} = $op;
        }
        if ($map eq "generic" && !exists($GENERIC_OP_TO_FUNC{$op})) {
            $GENERIC_OP_TO_FUNC{$op} = $function;
        }
        if ($map eq "index" && !exists($INDEX_OP_TO_FUNC{$op})) {
            $INDEX_OP_TO_FUNC{$op} = $function;
        }
      }
    }
  }
}

# Pass 2: parse the MenuOpSeq tables (op -> key binding) for every map.
for (my $i = 0; $i <= $#lines; $i++) {
  $_ = $lines[$i];
  if (/^(?:static )*const struct MenuOpSeq .*{ \/\* map: (.*) \*\//) {
    $map = $1;
    die "unknown map $map" unless $MAP_FUNC_TO_OP{$map};
    while (defined($_ = $lines[++$i])) {
      last if (/^}/);
      if (/{\s*(\w+)\s*,\s*"(.+)"\s*}/) {
        my ($op, $binding) = ($1, $2);

        # If the $op is NOT in the current map, but it IS in an
        # inherited map (index or generic), then we need to add a
        # stub entry in $MAP_FUNC_TO_OP and $MAP_OP_TO_SEQSET for
        # this case.
        unless ($MAP_OP_TO_SEQSET{$map}->{$op}) {
          if ($map eq "editor") {
            die "unknown OP $op for map $map";
          }

          my $function = $INDEX_OP_TO_FUNC{$op} // $GENERIC_OP_TO_FUNC{$op};
          unless ($function) {
            die "unknown OP $op for map $map";
          }

          $MAP_FUNC_TO_OP{$map}->{$function} = $op;
          $MAP_OP_TO_SEQSET{$map}->{$op} = {};
        }

        $binding =~ s/&/&amp;/;
        # for <key>, try CamelCasing into <Key>
        $binding =~ s/<(.)(.+)>/&lt;\U$1\E$2&gt;/;
        $binding =~ s/</&lt;/;
        $binding =~ s/>/&gt;/;
        $binding =~ s/ /&lt;Space&gt;/;
        $binding =~ s/^\\033/Esc /;
        $binding =~ s/^\\010/&lt;Backspace&gt;/;
        $binding =~ s/^\\177/&lt;Delete&gt;/;
        $binding =~ s/^\\(0\d+)$/'^'.chr(64+oct($1))/e;
        $binding =~ s/^\\(0\d+)(.)/'^'.chr(64+oct($1)) ." $2"/e;
        $binding =~ s/\\t/&lt;Tab&gt;/;
        $binding =~ s/\\r/&lt;Return&gt;/;
        $binding =~ s/\\n/&lt;Enter&gt;/;
        die "unknown key $binding" if $binding =~ /\\[^\\]|<|>/;
        $MAP_OP_TO_SEQSET{$map}->{$op}->{$binding} = 1;
      }
    }
  }
}

open XML, $xml or die "$xml: $!";
while (<XML>) {
  if (/__print_map\((.*)\)/) {
    my $map = $1;
    my $mapid = $1;
    my $maptitle = $1;
    $mapid =~ s/\s+/-/g;
    $maptitle =~ s/\b(\w)/\u$1/g;
    unless ($MAP_FUNC_TO_OP{$map}) {
      warn "map $map undefined";
      next;
    }
    print <<EOT;
<sect2 id="${mapid}-map">
<title>$maptitle Menu</title>
$DOC{$map}

<table id="tab-${mapid}-bindings">
<title>Default $maptitle Menu Bindings</title>
<tgroup cols="3">
<thead>
<row><entry>Function</entry><entry>Default key</entry><entry>Description</entry></row>
</thead>
<tbody>
EOT

    # Sort the map entries by function, then by binding
    foreach my $function (sort keys %{$MAP_FUNC_TO_OP{$map}}) {
      my $op = $MAP_FUNC_TO_OP{$map}->{$function};
      my $bindings = $MAP_OP_TO_SEQSET{$map}->{$op};

      if (scalar keys %{$bindings}) {
        foreach my $binding (sort keys %{$bindings}) {
          print "<row><entry><literal>&lt;" .
            $function .
            "&gt;</literal></entry><entry>" .
            $binding .
            "</entry><entry>" .
            $OPS{$op} .
            "</entry></row>\n";
        }
      }
      else {
        print "<row><entry><literal>&lt;" .
          $function .
          "&gt;</literal></entry><entry>" .
          "</entry><entry>" .
            $OPS{$op} .
          "</entry></row>\n";
      }
    }

    print <<EOT;
</tbody>
</tgroup>
</table>

</sect2>

EOT
    delete $MAP_FUNC_TO_OP{$map};
  } else {
    print;
  }
}
close XML;

warn "unprinted maps: ". join(" ", keys %MAP_FUNC_TO_OP) if %MAP_FUNC_TO_OP;
