#!/bin/sh --

dirs="/usr/local/lib/nls /usr/lib/nls /usr/local/share/nls /usr/share/nls"
dirs="$dirs /usr/local/lib/i18n /usr/lib/i18n /usr/local/share/i18n"
dirs="$dirs /usr/share/i18n"

rm -f ./charsets.list

for d in $dirs ; do
  [ -d $d/charmaps ] && ./parse_i18n ./ $d/charmaps/* >> ./charsets.list
done
