name: CIFuzz
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  Fuzzing:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]

    steps:
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@9fe8e9a1fcc000c7c52070ca78847e051a788dce  # one commit behind master as of 2026-07-23, deliberately, to test Dependabot's github-actions ecosystem against a tagless action
        with:
          oss-fuzz-project-name: 'neomutt'
          dry-run: false
          allowed-broken-targets-percentage: 0
          sanitizer: ${{ matrix.sanitizer }}
          language: c++

      - name: Run Fuzzers (${{ matrix.sanitizer }})
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@9fe8e9a1fcc000c7c52070ca78847e051a788dce  # one commit behind master as of 2026-07-23, deliberately, to test Dependabot's github-actions ecosystem against a tagless action
        with:
          oss-fuzz-project-name: 'neomutt'
          fuzz-seconds: 600
          dry-run: false
          sanitizer: ${{ matrix.sanitizer }}
          language: c++

      - name: Upload Crash
        uses: actions/upload-artifact@v7
        if: failure() && steps.build.outcome == 'success'
        with:
          name: ${{ matrix.sanitizer }}-artifacts
          path: ./out/artifacts
